[package]
name = "glacier_dev"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.8.0"
glam = "0.29.0"
glacier_resource = { path = "../glacier_resource" }
image = "0.25.4"
rerun = "0.19.0"
