[package]
name = "glacier_reflect"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.28.2", features = [
    "full",
    "rt",
    "rt-multi-thread",
    "time",
    "net",
] }
paste = "1.0.15"
glacier_util = { path = "../glacier_util" }
