[package]
name = "glacier_sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
glacier_fs = { path = "../glacier_fs" }
glacier_reflect = { path = "../glacier_reflect" }
glacier_reflect_swbf2 = { path = "../glacier_reflect_swbf2" }
glacier_util = { path = "../glacier_util" }
