[package]
name = "glacier_store"
version = "0.1.0"
edition = "2021"

[dependencies]
glacier_util = { path = "../glacier_util" }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
